### ISSUE TITLE
Finalize Markdown file spec and test for it

### ISSUE THREAD

**Issue by terror** [terror/threader#4]
Markdown files currently need to be written in a certain way in order to get outputted as a Twitter thread properly, that is:

```
## Title (Heading 2)
> Individual Tweets (Blockquote)
```

Delimiting individual tweets by a newline (\n) would probably be better? Anyways, finalize this and add some lightweight unit tests for `file.parse`.

**Comment by casey** [comment]
I like the idea of tweets with blank lines `\n\n`, since then the input would be in a format that I could post to my blog. I.e. write a blog post where each paragraph is a tweet, and then tweet it with threader and also post it to my blog. (Since my blog posts are also written in markdown.)

**Comment by terror** [comment]
> I like the idea of tweets with blank lines `\n\n`, since then the input would be in a format that I could post to my blog. I.e. write a blog post where each paragraph is a tweet, and then tweet it with threader and also post it to my blog. (Since my blog posts are also written in markdown.)

Agreed. This has been implemented in #9.

Looking to fix #2 before this is actually usable.
